source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.5'

# Use sqlite3 as the database for Active Record
# 編集 SQLiteのバージョンを指定　開発時のみSQLiteを使用するように変更
group :development do
  gem 'sqlite3'
end

# Use SCSS for stylesheets
# 編集 4.0.5以上なら最新版をインストール
gem 'sass-rails', '4.0.5'

# Use Uglifier as compressor for JavaScript assets
# 編集 2.1.1以上なら最新版をインストール
gem 'uglifier', '2.1.1'

# Use CoffeeScript for .js.coffee assets and views
# 編集 4.0.1以上なら最新版をインストール
gem 'coffee-rails', '4.0.1'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
# 編集 Jqueryライブラリのバージョンを指定
gem 'jquery-rails' , '3.0.4'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
